shell /usr/bin/zsh

#
kitty_mod ctrl+shift

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

#FONT
font_family Hack Nerd Font
bold_font Hack Nerd Font Bold
italic_font Hack Nerd Font Bold
bold_italic_font Hack Nerd Font Bold Italic

font_size 12

#TRANSPARENCY
background_opacity 0.9

#TAB
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

